export const queryKeys = {
  profiles: ["profiles"] as const,
  salesReps: ["salesReps"] as const,
  leads: (filters?: object) => ["leads", filters] as const,
  lead: (id: string) => ["lead", id] as const,
  queueLeads: ["queueLeads"] as const,
  splitRules: ["splitRules"] as const,
  deals: (repId?: string) => ["deals", repId] as const,
  clients: ["clients"] as const,
  client: (id: string) => ["client", id] as const,
  clientNotes: (id: string) => ["clientNotes", id] as const,
  activities: ["activities"] as const,
  payments: ["payments"] as const,
  dashboardKpis: (userId?: string) => ["dashboardKpis", userId] as const,
  revenueTrend: (userId?: string) => ["revenueTrend", userId] as const,
  activityVolume: (userId?: string) => ["activityVolume", userId] as const,
  leadsBySource: (userId?: string) => ["leadsBySource", userId] as const,
  pipelineFunnel: (userId?: string) => ["pipelineFunnel", userId] as const,
  splitEfficiency: ["splitEfficiency"] as const,
  activityFeed: (userId?: string) => ["activityFeed", userId] as const,
  leaderboard: (period: string) => ["leaderboard", period] as const,
  commissions: ["commissions"] as const,
  compPlans: ["compPlans"] as const,
  accounting: ["accounting"] as const,
  settings: ["settings"] as const,
  notifications: (userId: string) => ["notifications", userId] as const,
};
